# Generated by Django 3.1.12 on 2024-12-18 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mytool', '0002_auto_20241218_1939'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='firstdb',
            table='mytool_firstdb',
        ),
    ]
